import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Header } from "./components/Header";
import SupabaseListener from "./components/SupabaseListener";
// import { SupabaseListener } from "./components/SupabaseListener";
// import { Auth } from "./auth/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session, // ここにsessionを追加
}: Readonly<{
  children: React.ReactNode;
  session: any; // 適切な型に置き換えてください
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <StoreProvider>
        <SupabaseListener />

        {/* <Header /> */}
          {/* <Auth /> */}
          {/* <CamperVanPage /> */}
          
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
